export default function veiculosTabelas() {
  return [
          `CREATE TABLE IF NOT EXISTS veiculos (
              id INTEGER PRIMARY KEY,
              obra_id INTEGER,
              prefixo TEXT,
              tipo TEXT,
              placa TEXT,
              modelo TEXT,
              marca TEXT,
              ano INTEGER,
              imagem TEXT,
              data_sincronizacao TEXT,
              sync_status INTEGER DEFAULT 0,
              created_at TEXT              
            );`,

          `CREATE TABLE IF NOT EXISTS veiculos_diario_bordo (
              id INTEGER PRIMARY KEY,
              id_local TEXT,
              ciclo_status TEXT DEFAULT 'ABERTO',
              horas_trabalhadas_minutos INTEGER DEFAULT 0,
              descricao_encerramento TEXT,
              id_obra INTEGER,
              id_veiculo INTEGER,
              id_user INTEGER,
              user_create TEXT,
              user_edit TEXT,
              data_cadastro TEXT,
              horario_inicial TEXT,
              horimetro_inicial TEXT,
              hodometro_inicial TEXT,
              horario_final TEXT,
              horimetro_final TEXT,
              hodometro_final TEXT,
              descricao_atividade TEXT,
              arquivo_app TEXT,
              sync_status INTEGER DEFAULT 0,
              data_sincronizacao TEXT,
              created_at TEXT,
              deleted_at TEXT,
              updated_at TEXT
            );`,

          //ok
          `CREATE TABLE IF NOT EXISTS veiculo_checklist (
              id INTEGER PRIMARY KEY,
              id_veiculo INTEGER,
              nome_checklist TEXT,
              situacao TEXT,
              deleted_at TEXT,
              sync_status INTEGER DEFAULT 0,
              data_sincronizacao TEXT,
              created_at TEXT, 
              updated_at TEXT,
              user_create TEXT,
              user_edit TEXT
            );`,

          `CREATE TABLE IF NOT EXISTS veiculo_checklist_itens (
              id INTEGER PRIMARY KEY,
              id_checklist INTEGER,
              id_veiculo INTEGER,
              nome_servico TEXT,
              periodo_maq_vei INTEGER,
              alerta_venci INTEGER,
              tipo_itens TEXT,
              periodo_dias INTEGER,
              alert_venc_dias INTEGER,
              user_create TEXT,
              user_edit TEXT,
              situacao TEXT, 
              sync_status INTEGER DEFAULT 0,
              data_sincronizacao TEXT,
              created_at TEXT,
              deleted_at TEXT,
              updated_at TEXT
            );`,

          `CREATE TABLE IF NOT EXISTS veiculo_checklist_itens_realizados (
              id INTEGER PRIMARY KEY,
              id_obra INTEGER,
              id_checklist INTEGER,
              id_local TEXT,
              id_checklist_itens INTEGER,
              id_veiculo INTEGER,
              data_cadastro TEXT,
              status TEXT,
              arquivo_app TEXT,
              user_create TEXT,
              horimetro_atual INTEGER,
              horimetro_novo INTEGER,
              quilometragem_atual INTEGER,
              quilometragem_nova INTEGER,
              observacao TEXT,
              sync_status INTEGER DEFAULT 0,
              data_sincronizacao TEXT,
              created_at TEXT,
              deleted_at TEXT,
              updated_at TEXT
            );`,

          `CREATE TABLE IF NOT EXISTS veiculo_checklist_itens_servicos (
              id INTEGER PRIMARY KEY,
              id_obra INTEGER,
              id_veiculo INTEGER,
              id_checklist INTEGER,
              id_local TEXT,
              status TEXT,
              status_ciclo TEXT DEFAULT 'ABERTO',
              tipo_checklist TEXT DEFAULT 'ABERTURA',
              id_abertura_vinculada TEXT,
              data_fechamento TEXT,
              anomalia_offline INTEGER DEFAULT 0,
              foto_extra_1 TEXT,
              desc_extra_1 TEXT,
              foto_extra_2 TEXT,
              desc_extra_2 TEXT,
              foto_extra_3 TEXT,
              desc_extra_3 TEXT,
              foto_extra_4 TEXT,
              desc_extra_4 TEXT,
              data_cadastro TEXT,       
              user_create TEXT,
              user_edit TEXT,
              sync_status INTEGER DEFAULT 0,
              data_sincronizacao TEXT,
              created_at TEXT,
              deleted_at TEXT,
              updated_at TEXT,
              id_horimetro INTEGER,
              id_quilometragem INTEGER
            );`,

          `CREATE TABLE IF NOT EXISTS veiculo_checklist_evidencias (
              id INTEGER PRIMARY KEY AUTOINCREMENT,
              id_local TEXT,
              parent_tabela TEXT,
              parent_id_local TEXT,
              campo_foto TEXT,
              arquivo_local TEXT,
              arquivo_app TEXT,
              arquivo_servidor TEXT,
              user_create TEXT,
              user_edit TEXT,
              created_at TEXT,
              updated_at TEXT,
              sync_error TEXT,
              sync_attempts INTEGER DEFAULT 0,
              synced_at TEXT,
              sync_status INTEGER DEFAULT 0,
              data_sincronizacao TEXT
            );`,

          `CREATE INDEX IF NOT EXISTS idx_veiculo_evidencias_parent ON veiculo_checklist_evidencias(parent_tabela, parent_id_local);`,
          `CREATE INDEX IF NOT EXISTS idx_veiculo_evidencias_sync ON veiculo_checklist_evidencias(sync_status);`,

          `CREATE TABLE IF NOT EXISTS veiculo_horimetro (
              id INTEGER PRIMARY KEY,
              id_local TEXT,
              veiculo_id INTEGER,
              id_funcionario INTEGER,
              id_obra INTEGER,
              user_create TEXT,
              user_edit TEXT,
              horimetro_atual INTEGER,
              horimetro_novo INTEGER,
              data_horimetro TEXT,
              sync_status INTEGER DEFAULT 0,
              data_sincronizacao TEXT,
              created_at TEXT,
              updated_at TEXT
            );`,

          `CREATE TABLE IF NOT EXISTS veiculo_quilometragems (
              id INTEGER PRIMARY KEY,
              id_local TEXT,
              veiculo_id INTEGER,
              id_funcionario INTEGER,
              user_create TEXT,
              id_obra INTEGER,
              data_quilometragem TEXT,
              quilometragem_atual TEXT,
              quilometragem_nova TEXT,
              sync_status INTEGER DEFAULT 0,
              data_sincronizacao TEXT,
              updated_at TEXT,
              created_at TEXT
            );`,

          `CREATE TABLE IF NOT EXISTS veiculo_abastecimentos (
              id INTEGER PRIMARY KEY,
              id_local TEXT,
              veiculo_id INTEGER,
              id_obra TEXT,
              id_funcionario TEXT,
              user_create TEXT,
              user_edit TEXT,
              data_abastecimento TEXT,
              km_anterior INTEGER,
              km_atual INTEGER,
              hr_anterior INTEGER,
              hr_atual INTEGER,
              fornecedor TEXT,
              combustivel TEXT,
              tipo TEXT,
              quantidade REAL,
              valor_do_litro REAL,
              valor_total REAL,
              arquivo_app TEXT,
              sync_status INTEGER DEFAULT 0,
              data_sincronizacao TEXT,
              created_at TEXT,
              updated_at TEXT
            );`,
            
          `CREATE TABLE IF NOT EXISTS veiculos_locacaos (
              id INTEGER PRIMARY KEY,
              id_obra INTEGER,
              veiculo_id INTEGER,
              id_obraDestino INTEGER,
              id_funcionario INTEGER,
              id_funcionario_destino INTEGER,
              tipo_veiculo TEXT,
              data_inicio TEXT,
              data_prevista TEXT,
              data_fim TEXT,
              data_sincronizacao TEXT,
              sync_status INTEGER DEFAULT 0,
              created_at TEXT,
              updated_at TEXT
            );`,

          // Catalogos de manutencao preventiva (somente DOWNLOAD do MySQL)
          `CREATE TABLE IF NOT EXISTS veiculo_preventivas (
              id INTEGER PRIMARY KEY,
              id_veiculo INTEGER,
              nome_preventiva TEXT,
              nome_servico TEXT,
              tipo_veiculo TEXT,
              situacao TEXT,
              periodo INTEGER,
              tipo TEXT,
              alerta_venci INTEGER,
              user_create TEXT,
              user_edit TEXT,
              sync_status INTEGER DEFAULT 0,
              data_sincronizacao TEXT,
              created_at TEXT,
              updated_at TEXT,
              deleted_at TEXT
            );`,

          `CREATE TABLE IF NOT EXISTS veiculo_preventivas_itens_realizadas (
              id INTEGER PRIMARY KEY,
              id_veiculo INTEGER,
              fornecedor_id INTEGER,
              id_obra INTEGER,
              id_preventiva INTEGER,
              id_motorista INTEGER,
              tipo TEXT,
              nf_pecas TEXT,
              nf_mao_obra TEXT,
              valor_do_servico REAL,
              valor_da_mao_obra REAL,
              total_valor_servico REAL,
              quilometragem_atual INTEGER,
              quilometragem_nova INTEGER,
              campo_calc_km INTEGER,
              horimetro_atual INTEGER,
              horimetro_proximo INTEGER,
              campo_cal_hr INTEGER,
              data_de_execucao TEXT,
              data_previsao_termino TEXT,
              data_conclusao TEXT,
              campo_cal_mes INTEGER,
              data_de_vencimento TEXT,
              descricao TEXT,
              status_realizado TEXT,
              user_create TEXT,
              user_edit TEXT,
              sync_status INTEGER DEFAULT 0,
              data_sincronizacao TEXT,
              created_at TEXT,
              updated_at TEXT,
              deleted_at TEXT
            );`,

          `CREATE INDEX IF NOT EXISTS idx_veiculo_preventivas_veiculo ON veiculo_preventivas(id_veiculo);`,
          `CREATE INDEX IF NOT EXISTS idx_veiculo_preventivas_itens_veiculo ON veiculo_preventivas_itens_realizadas(id_veiculo);`,
          `CREATE INDEX IF NOT EXISTS idx_veiculo_preventivas_itens_preventiva ON veiculo_preventivas_itens_realizadas(id_preventiva);`,

            `CREATE TABLE IF NOT EXISTS veiculos_alugados_checklists (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                id_obra INTEGER,
                veiculo_id INTEGER,
                id_user INTEGER,
                user_create TEXT,
                user_edit TEXT,
                placa TEXT,
                modelo TEXT,
                horario TEXT,
                km_anterior TEXT,
                km TEXT,
                nivel_oleo INTEGER,
                nivel_agua INTEGER,
                observacoes TEXT,
                data_cadastro TEXT,
                situacao TEXT,                
                foto_hodometro TEXT,
                foto_carro_frente TEXT,
                foto_carro_traseira TEXT,
                foto_carro_esquerda TEXT,
                foto_carro_direita TEXT,
                foto_avaria_1 TEXT,
                foto_avaria_2 TEXT,
                sync_status INTERGER DEFAULT 0,
                created_at TEXT,
                updated_at TEXT,
                deleted_at TEXT                
            );`, ];
}
